<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" >
    <meta http-equiv="X-UA-Compatible" content="IE=edge" >
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <title>Privacy</title>
    <link rel="stylesheet" href="styleproject.css" >

    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com" >
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin >
    <link
      href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@100;300;400;700;900&display=swap"
      rel="stylesheet"
    >
    <!-- JS scripts-->
    <script src="app.js" async></script>
  </head>
  <body>
    <!--Header-->
    <?php include ("header.php");?>

    <div id="main">
    <?php include ("sidemenu.php");?>

    <div id="maincontent">
        <div class="content" id="browsecontent">
          <h3>
            At David's Adoption Service, we take the privacy and security of our
            users very seriously. We promise that any information you provide to
            us will not be sold or misused in any way. We also take great care
            to protect the website builder from any incorrect information that
            may be posted by pet owners. Rest assured that your personal
            information is in good hands with us.
          </h3>

          <p style="font-size: smaller">References:</p>
          <p style="font-size: smaller">
            The text on cat care and dog care was generated by chatGPT
          </p>
        </div>
      </div>
    </div>
    <?php include ("footer.php");?>

  </body>
</html>
